#!/usr/bin/env python
# Original author: Francesco Ambrosetti, modified by Daniil Lepikhov

from genericpath import exists
import math
import h5py
import re
import random
import os
import glob
import argparse
from sklearn.model_selection import train_test_split
import numpy as np
import random

arg_parser = argparse.ArgumentParser(
    description="This script combines every h5 files provided in the --features-path argument\
    into one file (--combined-h5). The h5 file is split into train, validation and test with the proportions provided by\
    --proportions argument and dumps the hdf5 for each dataset into the output folder (still to be defined)."
)
arg_parser.add_argument("--features-path", "-f",
    help="Path to the folder containing all h5 features generated by the 4/generate_features.py file.",
    default="/projects/0/einf2380/data/pMHCI/features_output_folder/hla_a_02_01_9_length_peptide/"
)
arg_parser.add_argument("--combined-h5", "-c",
    help="Name of the file dumped in the data/hdf5/cnn/combined/ folder.",
    default="hla_02_01_09_length_combined.hdf5"
)

arg_parser.add_argument("--proportions", "-p",
    help="Proportions of train, validation and test. Default 70, 20, 10",
    nargs="+",
    type=float,
    default=[0.7, 0.2, 0.1]
)

a = arg_parser.parse_args()

# Define the proportions based on the arguments provided:
train_p = a.proportions[0]
validation_p = a.proportions[1]
test_p = a.proportions[2]

# Change the combined_path and output_h5:
combined_h5_path = f"/projects/0/einf2380/data/pMHCI/features_output_folder/hla_a_02_01_9_length_peptide/combined/{a.combined_h5}"
output_h5_path = "/projects/0/einf2380/data/pMHCI/features_output_folder/hla_a_02_01_9_length_peptide/splits/"

__author__ = "Francesco Ambrosetti"
__email__ = "ambrosetti.francesco@gmail.com"

def h5_symlinks(input_path):
    """Combines HDF5 files from the input_path folder
    into a dictionaries of symlinks which then will be splited.
    """
    hfiles = glob.glob(f"{input_path}*.hdf5")
    symlinks = {}
    for hfile in hfiles:
        caseIDs = read_caseIDS_from_hfile(hfile)
        for caseID in caseIDs:
            symlinks[caseID] = hfile
    return symlinks


def read_caseIDS_from_hfile(hfile):
    """Read a hdf5 file and return the list of
    keys.
    f5_file = path to the hdf5 file"""
    caseIDs = []
    with h5py.File(hfile, 'r') as h5:
        caseIDs = list(h5.keys())
    return caseIDs

def split_cases(all_cases):
    """Get the training and validation.
    complete_hfile_path: path to the HDF5 file containing all
    features of every models.
    """

    # Read files
    print(f'Loaded pMHCI complexes: {len(all_cases)}')

    # Random split of all_cases:
    random.shuffle(all_cases)
    all_cases = np.array(all_cases)
    ds_l = all_cases.shape[0]
    train_ids, validation_ids, test_ids = np.split( # returns [0:train_p*len], [train_p*len:val_p*len], [val_p*len:]
        all_cases, 
        [
            int(train_p*ds_l),
            int((train_p+validation_p)*ds_l),
        ]
    )

    print(f'Training set: {len(train_ids)}')
    print(f'Validation set: {len(validation_ids)}')
    print(f'Test set: {len(test_ids)}')

    return train_ids, validation_ids, test_ids


def save_train_valid(train_idx, val_idx, test_idx, symlinks, path_out_folder):
    """Save two subsets of the original hdf5 files for containing
    training and validation sets.
    the output file names are: train.hdf5, valid.hdf5

    train_idx = caseIDs for the training set (from split_train())
    val_idx = casedIDs for the validation set (from split_train())
    out_folder = path to the output folder
    """

    # Create new hd5f files for the training and validation
    train_h5 = h5py.File(os.path.join(path_out_folder, 'train.hdf5'), 'w')
    val_h5 = h5py.File(os.path.join(path_out_folder, 'valid.hdf5'), 'w')
    test_h5 = h5py.File(os.path.join(path_out_folder, 'test.hdf5'), 'w')

    print("### Creating train.hdf5 file ###") 
    for i in train_idx:
        symlink_in_h5(i, symlinks[i], train_h5) 

    print("### Creating validation.hdf5 file ###") 
    for i in val_idx:
        symlink_in_h5(i, symlinks[i], val_h5) 

    print("### Creating test.hdf5 file ###") 
    for i in test_idx:
        symlink_in_h5(i, symlinks[i], test_h5) 

    train_h5.close()
    val_h5.close()
    test_h5.close()


def symlink_in_h5(idx, f1_path, f2):
    """Copy the selected keys (idx) of one hdf5 (f1) file into
     another hdf5 file (f2)
     idx = list of keys to copy
     f1 = handle of the first hdf5 file
     f2 = handle of the the second hdf5 file"""

    print(f'symlink: {idx}')

    # Get the name of the parent for the group we want to copy
    f1 = h5py.File(f1_path, "r")
    group_path = f1[idx].name

    # Copy
    f2[group_path] = h5py.ExternalLink(f1_path, group_path)
    f1.close()


if __name__ == '__main__':
    # Combine the h5 files:
    symlinks = h5_symlinks(a.features_path)
    all_cases = list(symlinks.keys())

    # Get training and validation keys
    print("spliting cases...")
    tr, va, t = split_cases(all_cases)

    # save keys into files
    with open('train_caseids.txt', 'w') as x:
        for element in tr:
            x.write(element)
            x.write('\n')
    with open('valid_caseids.txt', 'w') as y:
        for ele in va:
            y.write(ele)
            y.write('\n')
    with open('test_caseids.txt', 'w') as y:
        for ele in t:
            y.write(ele)
            y.write('\n')

    # create training and validation hdf5 files
    save_train_valid(tr, va, t,symlinks, output_h5_path)